package com.windowhyun.health.core.designsystem.theme

import androidx.compose.ui.graphics.Color

// 라이트
val md_light_primary = Color(0xFF2E6B4F)
val md_light_onPrimary = Color(0xFFFFFFFF)
val md_light_primaryContainer = Color(0xFFB4F1CD)
val md_light_onPrimaryContainer = Color(0xFF002114)
val md_light_secondary = Color(0xFF4E6355)
val md_light_onSecondary = Color(0xFFFFFFFF)
val md_light_secondaryContainer = Color(0xFFD1E8D6)
val md_light_onSecondaryContainer = Color(0xFF0C1F14)
val md_light_tertiary = Color(0xFF3A6470)
val md_light_onTertiary = Color(0xFFFFFFFF)
val md_light_tertiaryContainer = Color(0xFFBEEAF8)
val md_light_onTertiaryContainer = Color(0xFF001F27)
val md_light_error = Color(0xFFBA1A1A)
val md_light_onError = Color(0xFFFFFFFF)
val md_light_errorContainer = Color(0xFFFFDAD6)
val md_light_onErrorContainer = Color(0xFF410002)
val md_light_background = Color(0xFFFBFDF8)
val md_light_onBackground = Color(0xFF191C1A)
val md_light_surface = Color(0xFFFBFDF8)
val md_light_onSurface = Color(0xFF191C1A)
val md_light_surfaceVariant = Color(0xFFDCE5DC)
val md_light_onSurfaceVariant = Color(0xFF404943)
val md_light_outline = Color(0xFF707972)

// 다크
val md_dark_primary = Color(0xFF99D5B2)
val md_dark_onPrimary = Color(0xFF003825)
val md_dark_primaryContainer = Color(0xFF145138)
val md_dark_onPrimaryContainer = Color(0xFFB4F1CD)
val md_dark_secondary = Color(0xFFB5CCBA)
val md_dark_onSecondary = Color(0xFF213528)
val md_dark_secondaryContainer = Color(0xFF374B3E)
val md_dark_onSecondaryContainer = Color(0xFFD1E8D6)
val md_dark_tertiary = Color(0xFFA2CEDC)
val md_dark_onTertiary = Color(0xFF023541)
val md_dark_tertiaryContainer = Color(0xFF214C58)
val md_dark_onTertiaryContainer = Color(0xFFBEEAF8)
val md_dark_error = Color(0xFFFFB4AB)
val md_dark_onError = Color(0xFF690005)
val md_dark_errorContainer = Color(0xFF93000A)
val md_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_dark_background = Color(0xFF111412)
val md_dark_onBackground = Color(0xFFE1E3DF)
val md_dark_surface = Color(0xFF111412)
val md_dark_onSurface = Color(0xFFE1E3DF)
val md_dark_surfaceVariant = Color(0xFF404943)
val md_dark_onSurfaceVariant = Color(0xFFC0C9C1)
val md_dark_outline = Color(0xFF8A938C)
